name: nginx-domains

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:80/tcp
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: always

  bind:
    user: bind
    build:
      context: ./bind
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf:ro
      - ./bind/zones:/etc/bind/zones:ro
    environment:
      - BIND9_USER=bind
      - TZ=UTC
    restart: always
