- name: Install apache package
  ansible.builtin.package:
    name: "{{ apache_package }}"
    state: present

- name: Render template onto webserver
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: u=r,g=r,o=r
  notify: Reload apache daemon
