global:
  scrape_interval: 15s

scrape_configs:
  # gather statistics for the server itself
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  # gather statistics for the demo servers, hosted by prometheus
  # specifically for demo purposes.
  - job_name: demo_servers
    static_configs:
      - targets:
          - demo.promlabs.com:10000
          - demo.promlabs.com:10001
          - demo.promlabs.com:10002
  # also a statistics from localhost, about system that you are running
  # (powered by node_exporter)
  - job_name: localhost_node
    static_configs:
      - targets:
          # ip of a gateway, see docker-compose.yaml
          - 10.210.210.1:9100
