name: prometheus-grafana-integration
version: "3.8"

services:
  # prometheus-server is accessable via dns
  # or http://10.210.210.2:9090 url
  prometheus-server:
    build:
      context: ./prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      monitoring:
        ipv4_address: 10.210.210.2
    restart: always

  grafana-server:
    # run as root inside the container
    user: "0"
    build:
      context: ./grafana
    ports:
      - 3000:3000/tcp
    volumes:
      - ./.volumes/grafana:/var/lib/grafana:rw
    networks:
      monitoring:
        ipv4_address: 10.210.210.3
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 10.210.210.0/24
          gateway: 10.210.210.1
